// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANSNdKVifvXHUOzHQExXAKVTC8_C_XgVs',
    appId: '1:185069647989:web:f2b6e2fa7b7783504d203c',
    messagingSenderId: '185069647989',
    projectId: 'koreatravelapp',
    authDomain: 'koreatravelapp.firebaseapp.com',
    storageBucket: 'koreatravelapp.firebasestorage.app',
    measurementId: 'G-X1ZF11EY5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp7hdFl1jlRF6Y8GWgcQuMEebfqKf1xNk',
    appId: '1:185069647989:android:5d7545629805df914d203c',
    messagingSenderId: '185069647989',
    projectId: 'koreatravelapp',
    storageBucket: 'koreatravelapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAoX31KjF07AkG-6XFcF0qOKoAmwBY1U0',
    appId: '1:185069647989:ios:9011d3ad6fd0f79b4d203c',
    messagingSenderId: '185069647989',
    projectId: 'koreatravelapp',
    storageBucket: 'koreatravelapp.firebasestorage.app',
    iosBundleId: 'com.example.koreaTravelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAoX31KjF07AkG-6XFcF0qOKoAmwBY1U0',
    appId: '1:185069647989:ios:9011d3ad6fd0f79b4d203c',
    messagingSenderId: '185069647989',
    projectId: 'koreatravelapp',
    storageBucket: 'koreatravelapp.firebasestorage.app',
    iosBundleId: 'com.example.koreaTravelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANSNdKVifvXHUOzHQExXAKVTC8_C_XgVs',
    appId: '1:185069647989:web:9d3d24279596f9f54d203c',
    messagingSenderId: '185069647989',
    projectId: 'koreatravelapp',
    authDomain: 'koreatravelapp.firebaseapp.com',
    storageBucket: 'koreatravelapp.firebasestorage.app',
    measurementId: 'G-4WBM5PRST3',
  );
}
